[package]
name = "helios-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json.workspace = true
helios-core = { path = "../helios-core" }
helios-parser = { path = "../helios-parser" }
helios-detector = { path = "../helios-detector" }
helios-ingest = { path = "../helios-ingest" }
helios-enrichment = { path = "../helios-enrichment" }
helios-storage = { path = "../helios-storage" }
helios-api = { path = "../helios-api" }
helios-parser-syslog = { path = "../parsers/helios-parser-syslog" }
helios-parser-apache = { path = "../parsers/helios-parser-apache" }
helios-parser-nginx = { path = "../parsers/helios-parser-nginx" }
helios-parser-json = { path = "../parsers/helios-parser-json" }
helios-parser-cef = { path = "../parsers/helios-parser-cef" }
helios-parser-zookeeper = { path = "../parsers/helios-parser-zookeeper" }
helios-parser-spark = { path = "../parsers/helios-parser-spark" }
helios-parser-windows = { path = "../parsers/helios-parser-windows" }
helios-parser-android = { path = "../parsers/helios-parser-android" }
helios-parser-openssh = { path = "../parsers/helios-parser-openssh" }
helios-parser-proxifier = { path = "../parsers/helios-parser-proxifier" }

tokio.workspace = true

clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
helios-parser-evtx = { path = "../parsers/helios-parser-evtx" }
